/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import PetSupplyManagement.AddSearchSupplies;
import PetSupplyManagement.ViewSupplies;

/**
 *
 * @author Ammra Rizwan
 */
public class CashierInterface extends javax.swing.JFrame {

    /**
     * Creates new form CashierInterface
     */
    public CashierInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttView = new javax.swing.JButton();
        buttSearch = new javax.swing.JButton();
        buttAdd1 = new javax.swing.JButton();
        buttLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttAddview = new javax.swing.JButton();
        buttLogout1 = new javax.swing.JButton();
        buttview = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setText("Manager Panel");

        buttView.setBackground(new java.awt.Color(255, 51, 51));
        buttView.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttView.setText("View Pet Supplies");
        buttView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttViewActionPerformed(evt);
            }
        });

        buttSearch.setBackground(new java.awt.Color(255, 51, 51));
        buttSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttSearch.setText("Search by category");
        buttSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSearchActionPerformed(evt);
            }
        });

        buttAdd1.setBackground(new java.awt.Color(255, 51, 51));
        buttAdd1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttAdd1.setText("Add Products");
        buttAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAdd1ActionPerformed(evt);
            }
        });

        buttLogout.setBackground(new java.awt.Color(255, 51, 51));
        buttLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttLogout.setText("Log Out");
        buttLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttLogoutActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paws-8899970_960_720.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 530, 450));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setText("Cashier Panel");

        buttAddview.setBackground(new java.awt.Color(255, 51, 51));
        buttAddview.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttAddview.setText("Add/Search Products");
        buttAddview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAddviewActionPerformed(evt);
            }
        });

        buttLogout1.setBackground(new java.awt.Color(255, 51, 51));
        buttLogout1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttLogout1.setText("Log Out");
        buttLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttLogout1ActionPerformed(evt);
            }
        });

        buttview.setBackground(new java.awt.Color(255, 51, 51));
        buttview.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttview.setText("View Products");
        buttview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttview)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(buttLogout1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(buttAddview)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addComponent(buttview)
                .addGap(39, 39, 39)
                .addComponent(buttAddview)
                .addGap(37, 37, 37)
                .addComponent(buttLogout1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 360, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttViewActionPerformed

    }//GEN-LAST:event_buttViewActionPerformed

    private void buttSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSearchActionPerformed
    }//GEN-LAST:event_buttSearchActionPerformed

    private void buttAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttAdd1ActionPerformed

    private void buttLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttLogoutActionPerformed
        LoginManager lm = new LoginManager();
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttLogoutActionPerformed

    private void buttAddviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAddviewActionPerformed
        AddSearchSupplies as = new AddSearchSupplies();
        as.setVisible(true);
    }//GEN-LAST:event_buttAddviewActionPerformed

    private void buttLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttLogout1ActionPerformed
        LoginManager lm = new LoginManager();
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttLogout1ActionPerformed

    private void buttviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttviewActionPerformed
         ViewSupplies vs = new ViewSupplies();
        vs.setVisible(true);
    }//GEN-LAST:event_buttviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttAdd1;
    private javax.swing.JButton buttAddview;
    private javax.swing.JButton buttLogout;
    private javax.swing.JButton buttLogout1;
    private javax.swing.JButton buttSearch;
    private javax.swing.JButton buttView;
    private javax.swing.JButton buttview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
