/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import PetSupplyManagement.AddSearchSupplies;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ammra Rizwan
 */
public class LoginManager extends javax.swing.JFrame {

    /**
     * Creates new form Signin
     */
    public LoginManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        labPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        buttHome = new javax.swing.JButton();
        passPass = new javax.swing.JPasswordField();
        buttSignin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manager Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 270, -1));

        labEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labEmail.setText("Email");
        jPanel1.add(labEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        labPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labPassword.setText("Password");
        jPanel1.add(labPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 238, -1));

        buttHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttHome.setText("Home");
        buttHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttHomeActionPerformed(evt);
            }
        });
        jPanel1.add(buttHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));
        jPanel1.add(passPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 238, -1));

        buttSignin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttSignin.setText("Login");
        buttSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSigninActionPerformed(evt);
            }
        });
        jPanel1.add(buttSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 380, 370));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PAWSt.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttHomeActionPerformed
        Mainmenuinterface mn = new Mainmenuinterface();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttHomeActionPerformed

    private void buttSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSigninActionPerformed
        String Email = txtEmail.getText();
        String Password = new String(passPass.getPassword()).trim();

        if (Email.isEmpty() || Password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both Username and Password", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtEmail.getText().equals("manager@gmail.com") || passPass.getText().equals("manager")) {
            JOptionPane.showMessageDialog(this, "Successfully Logged in");
        } else {
            JOptionPane.showMessageDialog(this, "Entered Details are wrong");
        }

        ManagerInterface mi = new ManagerInterface();
        mi.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_buttSigninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttHome;
    private javax.swing.JButton buttSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labPassword;
    private javax.swing.JPasswordField passPass;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
