/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import PetSupplyManagement.AddSearchSupplies;
import PetSupplyManagement.ViewSupplies;

/**
 *
 * @author Ammra Rizwan
 */
public class ManagerInterface extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public ManagerInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttLogout = new javax.swing.JButton();
        buttCreatecash = new javax.swing.JButton();
        buttAdd1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setText("Manager Panel");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        buttLogout.setBackground(new java.awt.Color(255, 51, 51));
        buttLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttLogout.setText("Log Out");
        buttLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(buttLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 179, -1));

        buttCreatecash.setBackground(new java.awt.Color(255, 51, 51));
        buttCreatecash.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttCreatecash.setText("Create Cashier Account");
        buttCreatecash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCreatecashActionPerformed(evt);
            }
        });
        jPanel2.add(buttCreatecash, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        buttAdd1.setBackground(new java.awt.Color(255, 51, 51));
        buttAdd1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttAdd1.setText("Add/Search Products");
        buttAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAdd1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paws-8899970_960_720.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 530, 420));

        buttView.setBackground(new java.awt.Color(255, 51, 51));
        buttView.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttView.setText("View Products");
        buttView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttViewActionPerformed(evt);
            }
        });
        jPanel2.add(buttView, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAdd1ActionPerformed
        AddSearchSupplies as = new AddSearchSupplies();
        as.setVisible(true);
    }//GEN-LAST:event_buttAdd1ActionPerformed

    private void buttCreatecashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCreatecashActionPerformed
        CreateCashier cc = new CreateCashier();
        cc.setVisible(true);
    }//GEN-LAST:event_buttCreatecashActionPerformed

    private void buttLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttLogoutActionPerformed
        LoginManager lm = new LoginManager();
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttLogoutActionPerformed

    private void buttViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttViewActionPerformed
        ViewSupplies vs = new ViewSupplies();
        vs.setVisible(true);
    }//GEN-LAST:event_buttViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttAdd1;
    private javax.swing.JButton buttCreatecash;
    private javax.swing.JButton buttLogout;
    private javax.swing.JButton buttView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
